using Microsoft.AspNetCore.Http;

namespace Shoghlana.Core.DTOs;

public class FreelancerDTO
{
    // I don't need ID in dto because it's auto generated by EF >> when send freelancer to front as dto
    // , we want to send its id 
    public int Id { get; set; }

    public IFormFile[]? PersonalImageBytes { get; set; }

    public string Name { get; set; }

    public string Title { get; set; }

    public string? Address { get; set; }

    public string? OverView { get; set; }

    // should be uncommented and optional >> added on edit freelancer profile >> not added on freelancer creation >> use projectdto on adding , getprojectdto onretrieving
    public List<GetProjectDTO>? Portfolio { get; set; }

    public List<AddJobDTO>? WorkingHistory { get; set; }

    public List<ProposalDTO>? Proposals { get; set; }

    public List<SkillDTO>? Skills { get; set; }

    //public List<Notification>? notifications { get; set; }
}
