namespace Shoghlana.Core.DTOs;
public class GetFreelancerDTO
{

    // I don't need ID in dto because it's auto generated by EF >> when send freelancer to front as dto
    // , we want to send its id 
    public int Id { get; set; }

    public byte[]? PersonalImageBytes { get; set; }

    public string Name { get; set; }

    public string Title { get; set; }

    public string? Address { get; set; }

    public string? OverView { get; set; }

    public List<GetProjectDTO>? Portfolio { get; set; }

    public List<GetJobDTO>? WorkingHistory { get; set; }

    public List<GetProposalDTO>? Proposals { get; set; }

    public List<SkillDTO>? Skills { get; set; }

    //public List<Notification>? notifications { get; set; }

}
